import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>Next.js</a> with <a>MDX!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <Link href="/router" className={styles.card}>
            <h2>Route Learning &rarr;</h2>
            <p>file-folder route、Dynamic Route ( index routes, catch all routes ).</p>
          </Link>

          <Link href="/highlighting" className={styles.card}>
            <h2>Code Highlight  &rarr;</h2>
            <p>Highlight code in the mdx Docs with nightOwlLight themes</p>
          </Link>

          <Link
            href="/code-preview"
            className={styles.card}
          >
            <h2>MDX Code Preview &rarr;</h2>
            <p>Preview code in the MDX docs</p>
          </Link>

          <Link
            href="/404"
            className={styles.card}
          >
            <h2>404 Page &rarr;</h2>
            <p>
              Page Not Found......
            </p>
          </Link>
        </div>
      </main>
    </div>
  )
}

export default Home
