import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>Next.js</a> with <a>MDX!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <Link href="/router">
            <div className={styles.card}>
              <h2>Route Learning &rarr;</h2>
              <p>file-folder route、Dynamic Route ( index routes, catch all routes ).</p>
            </div>
          </Link>

          <Link href="/highlighting">
            <div className={styles.card}>
              <h2>Code Highlight  &rarr;</h2>
              <p>Highlight code in the mdx Docs with nightOwlLight themes</p>
            </div>
          </Link>

          <Link href="/code-preview">
            <div className={styles.card}>
              <h2>MDX Code Preview &rarr;</h2>
              <p>Preview code in the MDX docs</p>
            </div>
          </Link>

          <Link href="/404" >
            <div className={styles.card}>
              <h2>404 Page &rarr;</h2>
              <p>Page Not Found......</p>
            </div>
          </Link>
        </div>
      </main>
    </div>
  )
}

export default Home
